_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: ".output/mixtrain/model_0079999.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("coco_2017_train",)
SOLVER:
  STEPS: (2,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 5
INPUT:
  FORMAT: "RGB"
TEST:
  INFERENCE_TH_TEST: 0.5